language: java

cache:
  directories:
  - $HOME/.m2
  
jdk:
- oraclejdk8

sudo: false

# TODO: Remove the Strict Quote Escaping Flag once ACDM-472 is resolved
script: mvn test -Dorg.apache.jasper.compiler.Parser.STRICT_QUOTE_ESCAPING=false jspc:compile -B
